_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.3
            "6": 4.48.0
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
